name: echidna-test
on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/echidna-test.yml'
      - '*echidna.config.yml'
  workflow_dispatch:

jobs:
  test-echidna:
    runs-on: ubuntu-latest
    env:
      SOLC_REMAP: '@openzeppelin=/home/runner/work/echidna-test/echidna-test/node_modules/@openzeppelin'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install slither
        run: |
          pip3 install slither-analyzer --user
          echo "check installed slither version....."
          pip3 show slither-analyzer
      - name: Install solc
        env:
          SOLC_VERSION: 0.8.4
        run: |
          pip install solc-select
          solc-select install ${{ env.SOLC_VERSION }}
          solc-select use ${{ env.SOLC_VERSION }}
      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.5.1/echidna-test-v1.5.1-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test
      - name: List openzeppeline files
        run: |
          ls -l node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol
          pwd
      - name: Compile contract with solc
        run: |
          solc --bin -o /tmp/solcoutput ${{ env.SOLC_REMAP }} contracts/tests/EchidnaTest.sol

      - name: Run echidna test simpile
        run: |
          echidna-test contracts/tests/EchidnaERC1820.sol --contract EchidnaERC1820 --config echidna.config.yml

      - name: Run echina tests
        run: |
          echo cryticArgs: \[\"--solc-remaps\", \"${{ env.SOLC_REMAP }}\"\] > remap.config.yml
          cat remap.config.yml
          echidna-test contracts/tests/EchidnaTest.sol --contract EchidnaTest --config default-echidna.config.yml
